# baseURL = 'https://example.org/'
baseURL = 'https://yuhkih.github.io/hugo-hello/'
# languageCode = 'en-us'
languageCode = 'ja-JP'
title = 'My New Hugo Site'
theme = "hugo-book"
# publishDir = "docs"
